"""The catalogue: every machine and service line, ported from wonderbytech.com
(read 13 Sep 2026). Specs are verbatim from the original pages; the copy is
in the site's voice. Images: the maker's product images from the original
site, plus our own captures where the machine is in the building."""

MACHINES = [
    {
        "slug": "unitree-g1", "group": "humanoid", "details": ['machines/unitree-g1-d1.jpg', 'machines/unitree-g1-d2.jpg', 'machines/unitree-g1-d3.jpg'], "light": "machines/cut/unitree-g1.webp", "stage": "machines/unitree-g1-stage.jpg", "highlights": [('1.27 m tall', 'Human scale, room scale'), ('About 35 kg', 'With the battery in'), ('Up to 43 DOF', '23 on the standard build'), ('Dex3-1 hands', 'Three fingers, optional tactile sensing'), ('Jetson Orin', '40 TOPS on board'), ('3D LiDAR', 'Plus a depth camera'), ('About 2 hours', '9000 mAh quick-release battery'), ('18-month warranty', 'Secondary development on EDU')], "pos": "50% 62%", "maker": "Unitree", "name": "Unitree G1",
        "kind": "Humanoid robot", "status": "On our floor",
        "line": "A compact humanoid for research, development and the kind of demo people remember.",
        "intro": "We supply the G1 EDU configuration: the secondary-development version with Jetson Orin compute, the higher-DOF build and Dex3-1 dexterous hands. It's the one to quote when the project depends on hands and software, not just walking. One lives on our floor, so you can see it before you buy it.",
        "hero": "machines/unitree-g1-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Precision manipulation", "Dex3-1 three-fingered hands, optional tactile sensing, force-position hybrid control. The configuration for grasping and interaction work."),
            ("Autonomous navigation", "Depth camera and 3D LiDAR in a 1.27 m body, which makes it easy to evaluate in labs, showrooms and spaces built for people."),
            ("Research-grade compute", "NVIDIA Jetson Orin, secondary development, OTA updates. Custom software, embodied AI, perception work, platform evaluation."),
        ],
        "fits": [
            ("Universities and labs", "Embodied AI, human-robot interaction, locomotion research and teaching, with ROS 2 access and on-board compute."),
            ("Enterprise pilots", "We manage the pilot, the hardware and the support through the evaluation. Most enterprise enquiries start here."),
            ("Control and perception prototyping", "Teams building control systems, interaction logic or perception workflows who need a real body to test against."),
            ("Events and activations", "Trade shows and public demonstrations where presence and movement quality are the point."),
        ],
        "specs": [("Model", "Unitree G1 EDU"), ("Height", "About 1.27 m"), ("Weight with battery", "About 35 kg"), ("Degrees of freedom", "23 to 43 depending on configuration"), ("Waist DOF", "1, plus optional 2"), ("Hand DOF", "Dex3-1: 7, plus optional 2 wrist DOF"), ("Maximum knee torque", "120 N·m"), ("Arm maximum load", "About 3 kg"), ("Basic compute", "8-core high-performance CPU"), ("High-compute module", "NVIDIA Jetson Orin, 40 TOPS"), ("Sensing", "Depth camera and 3D LiDAR"), ("Wireless", "Wi-Fi 6, Bluetooth 5.2"), ("Audio", "4-microphone array, 5 W speaker"), ("Battery", "9000 mAh quick-release smart battery"), ("Runtime", "About 2 hours"), ("Secondary development", "Supported on EDU"), ("Warranty", "18 months")],
        "compare": ("G1 Standard vs G1 EDU", [("Active DOF", "23", "43, expandable"), ("AI compute", "8 TOPS", "40 TOPS, Jetson Orin"), ("Charging", "Manual", "Auto-dock"), ("Hands", "None", "Dex3-1 dexterous hand, optional wrist DOF"), ("Secondary development", "Not supported", "Supported"), ("Best fit", "Retail, demonstration", "Research, evaluation, development")]),
        "faq": [("Which version do you supply?", "The EDU. Unitree lists secondary development on EDU only, so for ROS 2 work, custom software or platform development it's the one to quote."), ("Where does it work best?", "Indoor, structured spaces: labs, showrooms, event floors. We check floor conditions, operating space, power and supervision before recommending a format."), ("Can you write software for it?", "Yes. Interface layers, perception workflows and application logic on the EDU platform, scoped as supply, a local pilot or a wider software job."), ("Lead time?", "Depends on configuration and Unitree availability. We confirm hardware timing, shipping and any software scope at quotation, not as a generic estimate.")],
        "price": "Quoted to order", "related": ["unitree-go2", "ubtech-cruzr-y1", "ubtech-cruzr-1s", "ubtech-cadebot"],
    },
    {
        "slug": "unitree-go2", "group": "humanoid", "details": ['machines/unitree-go2-d1.jpg', 'machines/unitree-go2-d2.jpg', 'machines/unitree-go2-d3.jpg'], "light": "machines/cut/unitree-go2.webp", "stage": "machines/unitree-go2-stage.jpg", "highlights": [('12 DOF', 'Three per leg'), ('About 15 kg', 'With the battery in'), ('Up to 5 m/s', '3.7 m/s rated'), ('About 40° climb', 'Stairs and rough ground'), ('4D LiDAR L2', '360° by 96° sensing'), ('8 to 12 kg payload', 'Room for your sensors'), ('2 to 4 hours', 'Long-endurance battery option'), ('Air, Pro, X, EDU', 'EDU for ROS 2 and the SDK')], "pos": "50% 62%", "maker": "Unitree", "name": "Unitree GO2",
        "kind": "Quadruped robot", "status": "Sourced to order",
        "line": "A robot dog for inspection, patrol and the ground wheels can't cover.",
        "intro": "We supply the whole GO2 range: Air, Pro, X and EDU. EDU is the one for ROS 2, SDK-level integration and the optional high-compute module; Air and Pro suit lighter operational and demonstration use, X the harder field work.",
        "hero": "machines/unitree-go2-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("All-terrain locomotion", "12 DOF, up to about 5 m/s, climbs about 40°, stairs and uneven ground. The reason it's relevant for inspection routes and patrol trials."),
            ("Sensing and autonomy", "Unitree 4D LiDAR L2, 360° × 96° recognition, obstacle avoidance and autonomous navigation in structured and semi-structured spaces."),
            ("AI research platform", "Secondary development, ROS 2, optional Jetson Orin module and payload capacity for custom devices on the EDU."),
        ],
        "fits": [
            ("Inspection and field operations", "Facilities teams, utilities and construction sites: slopes, stairs, rough ground and confined routes."),
            ("Research and education", "Legged locomotion, autonomous navigation, sensor fusion and teaching. EDU for anything that needs ROS 2 or the SDK."),
            ("Patrol and security", "Campuses and facilities trialling autonomous patrol with camera payloads."),
            ("Events and activations", "Where natural movement and presence are the engagement."),
        ],
        "specs": [("Model", "Unitree GO2 EDU"), ("Standing size", "About 70 × 31 × 40 cm"), ("Crouching size", "About 76 × 31 × 20 cm"), ("Weight with battery", "About 15 kg"), ("Degrees of freedom", "12, 3 per leg"), ("Maximum speed", "0 to 3.7 m/s, up to about 5 m/s in lab conditions"), ("Payload", "About 8 kg, maximum about 12 kg"), ("Maximum climb angle", "About 40°"), ("Peak joint torque", "About 45 N·m"), ("Basic compute", "8-core high-performance CPU"), ("High-compute module", "Optional NVIDIA Jetson Orin"), ("LiDAR", "Unitree 4D LiDAR L2"), ("Wireless", "Wi-Fi 6, Bluetooth, 4G depending on configuration"), ("Battery", "8000 mAh standard, optional 15000 mAh long-endurance"), ("Runtime", "About 2 to 4 hours depending on battery and configuration"), ("Secondary development", "Supported on EDU"), ("Warranty", "12 months")],
        "compare": ("Air, Pro, X and EDU", [("Onboard compute", "8-core CPU", "8-core CPU, plus optional Jetson Orin on EDU"), ("Payload", "About 7 to 8 kg, max 10 kg", "About 8 kg, max 12 kg"), ("Maximum speed", "2.5 to 3.5 m/s", "3.7 m/s, about 5 m/s peak"), ("Best fit", "Demonstration, lighter operations", "Field use, development, research")]),
        "faq": [("Which variant do I need?", "Lighter operational or demo use fits Air or Pro, harder field use fits X, and anything development-led needs EDU."), ("Stairs, slopes, outdoors?", "Yes. About 40° climb, mixed surfaces, gravel and stairs. We review the site, payload and routes first."), ("Do I need EDU for ROS 2?", "Yes, for ROS 2, custom software, SDK integration or platform evaluation."), ("Lead time?", "Configuration and Unitree availability decide it; we confirm at quotation.")],
        "price": "Quoted to order", "related": ["unitree-g1", "ubtech-cadebot", "ubtech-cruzr-1s"],
    },
    {
        "slug": "ubtech-cruzr-1s", "group": "service", "details": ['machines/ubtech-cruzr-1s-d1.jpg', 'machines/ubtech-cruzr-1s-d2.jpg', 'machines/ubtech-cruzr-1s-d3.jpg'], "light": "machines/cut/ubtech-cruzr-1s.webp", "stage": "machines/ubtech-cruzr-1s-stage.jpg", "highlights": [('11.6-inch touchscreen', 'HD, front and centre'), ('U-SLAM navigation', 'Dynamic obstacle avoidance'), ('Guided tours', 'Waypoints and routes'), ('Multilingual voice', 'Greets, answers, guides'), ('650 mm aisles', '15 mm obstacles, 8° climb'), ('8 hours working', '24 hours on standby'), ('Charges itself', 'Automatic return to dock'), ('Content playback', 'Promotions on the screen')], "maker": "UBTECH", "name": "UBTECH Cruzr 1S",
        "kind": "Service robot", "status": "On our floor",
        "line": "The reception robot. Greets, guides, plays your content and comes back to charge.",
        "intro": "Cruzr isn't a research platform; it's a front-of-house service robot for structured indoor spaces where a robot greets people, guides them on a route, shows content and does the repeatable part of reception without a hand on the controls. Ours works the door at 365 St Pauls Terrace.",
        "hero": "machines/ubtech-cruzr-1s-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Reception and guest interaction", "Voice, touchscreen, multilingual greeting and routine questions in lobbies, clinics, counters and foyers."),
            ("Guided tours and wayfinding", "U-SLAM navigation, waypoint tours and route guidance for museums, showrooms, exhibitions and visitor facilities."),
            ("Content and service workflows", "Media playback, patrol support and IoT linkage inside a defined indoor service model."),
        ],
        "fits": [
            ("Hospitality and reception", "Hotels, clinics and front-of-house environments where greeting, queue support and guidance are the service."),
            ("Guided tours and public venues", "Museums, showrooms, exhibitions and civic halls. For tray delivery in the same venue, see CadeBot."),
            ("Retail promotion", "Campaign playback and visitor engagement in stores and activations."),
            ("Public service", "Administrative halls and counters where reception and routine information are the job."),
        ],
        "specs": [("Model", "UBTECH Cruzr 1S"), ("Category", "Intelligent service robot, indoor commercial reception"), ("Display", "11.6\" HD interactive touchscreen"), ("Navigation", "U-SLAM autonomous navigation with dynamic obstacle avoidance"), ("Sensors", "LiDAR, RGB-D camera, infrared and ultrasonic"), ("Interaction", "Voice, touchscreen, cloud-connected service workflows"), ("Minimum aisle width", "About 650 mm"), ("Maximum obstacle", "About 15 mm"), ("Maximum climb", "About 8°"), ("Runtime", "Up to 8 hours working, up to 24 hours standby"), ("Charging", "Automatic return to charge"), ("Core workflows", "Reception, guided tours, advertising playback, patrol support, IoT linkage")],
        "compare": None,
        "faq": [("What is it for?", "Front-of-house: reception, guest interaction, guided tours and public information. Not open-ended robotics research."), ("Where does it work?", "Structured indoor spaces: lobbies, clinics, showrooms, exhibitions, reception areas. We review route width, floors and workflow first."), ("Tours and promotional content?", "Yes: guided tours, route guidance, advertising playback and visitor interaction are its core uses."), ("Does it charge itself?", "Yes, automatic return to charge, which is what makes all-day venue deployment workable.")],
        "price": "Quoted to your floor", "related": ["ubtech-cadebot", "ubtech-yanshee", "coffee-robot", "unitree-go2"],
    },
    {
        "slug": "ubtech-cadebot", "group": "service", "details": ['machines/ubtech-cadebot-d1.jpg', 'machines/ubtech-cadebot-d2.jpg', 'machines/ubtech-cadebot-d3.jpg'], "light": "machines/cut/ubtech-cadebot.webp", "stage": "machines/ubtech-cadebot-stage.jpg", "highlights": [('40 kg payload', 'Across three open trays'), ('21.5-inch display', 'FHD, customer-facing'), ('10.1-inch touch', 'Operator interface'), ('650 mm aisles', '15 mm obstacles, 5° slopes'), ('6 hours running', 'About 4 hours to charge'), ('LiDAR plus RGB-D', 'Two cameras, two ultrasonics'), ('1255 mm tall', '551 wide, 484 deep, 55 kg'), ('Voice prompts', 'Guidance and status on the move')], "pos": "50% 30%", "maker": "UBTECH", "name": "UBTECH CadeBot",
        "kind": "Delivery robot", "status": "On our floor",
        "line": "The tray robot. Three trays, 40 kg, a 21.5-inch screen, and it finds its own way to the table.",
        "intro": "CadeBot is a delivery and service robot for repeatable indoor routes: open trays for food, retail items and supplies, a big display for promotion or status, and autonomous navigation through aisles full of people. Two of them carry plates across our floor every service.",
        "hero": "machines/ubtech-cadebot-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Commercial delivery", "Open tray design, 40 kg payload across three trays, built for quick loading and repeatable movement through commercial spaces."),
            ("Display and guest communication", "21.5\" advertising display, 10.1\" touch interface and voice prompts: promotions, guidance, status or venue content."),
            ("Autonomous indoor navigation", "LiDAR, dual RGB-D cameras and ultrasonic sensing for routing and obstacle handling in tighter aisles."),
        ],
        "fits": [
            ("Restaurants and hotels", "Front-of-house delivery and service support on structured routes. For greeting and tours, see Cruzr."),
            ("Retail and public venues", "Stores, airports and public spaces where the robot moves items and shows messages."),
            ("Supermarkets", "Aisle-friendly assistance and promotional movement on a defined path."),
            ("Factories", "Internal material movement and light delivery in production or warehouse-adjacent spaces."),
        ],
        "specs": [("Model", "UBTECH CadeBot"), ("Category", "Smart service robot, indoor delivery"), ("Dimensions", "1255 mm high, 551 mm wide, 484 mm deep"), ("Weight", "55 kg"), ("Payload", "40 kg across 3 trays"), ("Advertising display", "21.5\" FHD, 1920 × 1080"), ("Touch interface", "10.1\" FHD, 1200 × 1920"), ("Minimum aisle width", "650 mm"), ("Maximum obstacle", "15 mm"), ("Maximum slope", "5°"), ("Runtime", "6 hours continuous, about 4 hours to full charge"), ("Sensors", "LiDAR ×1, RGB-D cameras ×2, ultrasonic ×2"), ("Core workflows", "Indoor delivery, public service support, promotional display, autonomous routes")],
        "compare": None,
        "faq": [("What is it for?", "Open-tray delivery and route execution with a customer-facing display, rather than the reception model Cruzr uses."), ("Where does it work?", "Restaurants, hotels, retail, airports and selected factory routes, where aisle width, floors and delivery logic can be defined."), ("Can it carry promotions as well as goods?", "Yes. The 21.5-inch display runs branded messaging, promotions or instructions while it delivers."), ("How much can it carry?", "40 kg across the three trays. We check that against your item sizes, load pattern and route.")],
        "price": "Quoted to your floor", "related": ["ubtech-cruzr-1s", "coffee-robot", "kitchen-robot", "unitree-go2"],
    },
    {
        "slug": "ubtech-cruzr-y1", "group": "service", "details": ['machines/ubtech-cruzr-y1-d1.jpg', 'machines/ubtech-cruzr-y1-d2.jpg', 'machines/ubtech-cruzr-y1-d3.jpg'], "light": "machines/cut/ubtech-cruzr-y1.webp", "stage": "machines/ubtech-cruzr-y1-stage.jpg", "highlights": [('Two 7-DOF arms', '750 mm reach each'), ('10 kg arm payload', 'Force control on every joint'), ('0 to 1800 mm lift', '850 mm vertical range'), ('Laser SLAM and VSLAM', 'Lidar, RGBD, ToF, bumpers'), ('1.5 m/s', 'Omnidirectional base'), ('±20 mm positioning', '±2° heading'), ('Swappable battery', 'Automatic charging too'), ('650 × 550 × 1700 mm', '90 kg plus')], "maker": "UBTECH", "name": "UBTECH Cruzr Y1",
        "kind": "Material handling robot", "status": "Sourced to order",
        "line": "A mobile dual-arm robot for the warehouse jobs between manual labour and fixed automation.",
        "intro": "Cruzr Y1 is for material handling, loading and unloading, depalletising and sorting in factories and logistics. Mobile navigation, two 7-DOF arms and a vertical lift, so one platform covers transport, loading and sorting instead of a cell for each.",
        "hero": "machines/ubtech-cruzr-y1-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Dual-arm handling", "Two 7-DOF arms, 750 mm reach, force control. Coordinated reach and controlled grasping for bins, cartons and pick-and-place."),
            ("Lift range", "Vertical lift with an 850 mm range and a 0 to 1800 mm working height, plus a waist tray, so one robot covers floor pickup to machine-side loading."),
            ("Navigation and autonomy", "Laser SLAM and VSLAM, lidar, RGBD and ToF, layered obstacle avoidance, automatic charging and a swappable battery for multi-shift work."),
        ],
        "fits": [
            ("Warehouse material handling", "Cartons, bins and containers on routes too variable for conveyors. Published envelope up to 650 × 450 × 400 mm."),
            ("Manufacturing loading and depalletising", "Approaching stations, working at several heights, moving between adjacent tasks."),
            ("Sorting", "Hard packs, soft packs and file-style items where item classes stay stable and routes change through the day."),
            ("Flexible automation", "One mobile handling robot across several work areas instead of separate fixed cells."),
        ],
        "specs": [("Model", "UBTECH Cruzr Y1"), ("Category", "Material handling robot, mobile embodied handling platform"), ("Weight", "90+ kg"), ("Overall size", "650 × 550 × 1700 mm"), ("Navigation", "Laser SLAM and VSLAM sensor fusion"), ("Wireless", "Wi-Fi, 5G"), ("Base", "Omnidirectional mobile chassis"), ("Travel speed", "Up to 1.5 m/s"), ("Lift module", "Vertical lift, 850 mm range, 0 to 1800 mm operating height"), ("Handling envelope", "Boxes and cartons up to 650 × 450 × 400 mm in the published examples"), ("Positioning accuracy", "±20 mm, ±2°"), ("Arms", "Dual, 7 DOF each, 750 mm"), ("Arm payload", "10 kg per the product document"), ("Arm control", "Force control standard, brakes on all 7 joints"), ("Sensors", "Head RGBD, dual wrist RGBD, dual binocular cameras, lidar, dual ToF arrays, bumper safety"), ("Power", "Automatic charging, swappable battery")],
        "compare": None,
        "faq": [("What is it for?", "Material handling: loading, unloading, depalletising and sorting in warehouses and factories. Not reception."), ("What can it handle?", "Box transport, carton handling, depalletising and sorting of hard packs, soft packs and documents. Fit depends on the workpiece, route, cycle and grip."), ("Does it navigate a warehouse on its own?", "Yes: laser SLAM plus VSLAM, with lidar, cameras, RGBD, ToF and bumper safety."), ("How do you assess fit?", "Task type, payload, workpiece size, lift height, aisle width, charging, shift pattern, and whether a mobile robot really beats fixed automation for the process.")],
        "price": "Quoted to order", "related": ["unitree-g1", "custom-automation", "ubtech-cruzr-1s", "ubtech-cadebot"],
    },
    {
        "slug": "ubtech-yanshee", "group": "education", "details": ['machines/ubtech-yanshee-d1.jpg', 'machines/ubtech-yanshee-d2.jpg', 'machines/ubtech-yanshee-d3.jpg'], "light": "machines/cut/ubtech-yanshee.webp", "stage": "machines/ubtech-yanshee-stage.jpg", "highlights": [('17 servos', 'Neck, arms, legs'), ('37 cm, 2.1 kg', 'Desk-sized humanoid'), ('Raspberry Pi 3B', '1 GB RAM, 16 GB eMMC'), ('8 MP camera', 'Up to 30 fps'), ('Python and Scratch', 'Linux, ROS concepts, GPIO'), ('9-axis IMU', 'Plus ultrasonic, IR, climate'), ('About 3 hours', '3000 mAh battery'), ('STM32 co-processor', 'Real-time joint control')], "maker": "UBTECH", "name": "UBTECH Yanshee",
        "kind": "Educational humanoid", "status": "Sourced to order",
        "line": "A real jointed humanoid for classrooms and labs, with Python, Scratch and ROS underneath.",
        "intro": "Yanshee is for education and research teams that need more than a toy but less than a full commercial humanoid: 17 servos, an 8 MP camera, Raspberry Pi compute and open access for Python, Scratch, Linux and ROS-based work.",
        "hero": "machines/ubtech-yanshee-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Humanoid motion", "17 DOF for head, arms and legs: walks, poses, dances and runs repeatable motion sequences for teaching kinematics and behaviour design."),
            ("Vision and interaction", "8 MP camera, microphones, speakers, IMU and environmental sensors for vision tasks and human-robot interaction exercises."),
            ("Open coding workflow", "Raspberry Pi 3B, Python and Scratch, ROS concepts, Linux tooling and GPIO for hardware extension."),
        ],
        "fits": [
            ("K-12 STEM programs", "Coding classes, sensor experiments, introductory AI and robotics clubs where code gets a visible physical response."),
            ("Universities and research labs", "A compact open humanoid for computer vision, interaction design and coursework before moving to larger hardware."),
            ("Competitions and public demos", "Expressive motion and interactive behaviour for competitions, exhibitions and outreach."),
            ("Maker and training labs", "GPIO, Linux access and a platform that extends for custom lessons and control experiments."),
        ],
        "specs": [("Model", "UBTECH Yanshee"), ("Category", "Humanoid educational robot, desktop AI and robotics platform"), ("Active DOF", "17: 1 neck, 6 arms, 10 legs"), ("Height and weight", "About 37 cm, about 2.1 kg"), ("Main compute", "Raspberry Pi 3B, 1 GB RAM, 16 GB eMMC"), ("Co-processor", "STM32 MCU for real-time joint control"), ("Camera", "8 MP HD, up to 30 fps"), ("Sensors", "9-axis IMU, ultrasonic, infrared, temperature, humidity, pressure"), ("Connectivity", "Wi-Fi 802.11 b/g/n, Bluetooth 4.1"), ("Battery", "3000 mAh, about 3 hours active"), ("Development access", "Python, Scratch, Linux, ROS concepts, GPIO")],
        "compare": None,
        "faq": [("Who buys it?", "Schools, universities, maker labs, coding workshops and research teams wanting a compact humanoid for teaching and early embodied-AI work."), ("Python and Scratch?", "Yes, both, which is why it suits entry-level teaching and more technical secondary development."), ("Advanced research?", "It's a teaching and prototyping platform. Larger projects move to hardware like the Unitree G1."), ("Where does it sit in a program?", "After uKit, alongside or after UGOT, before a full research humanoid.")],
        "price": "Quoted to order", "related": ["ubtech-ugot", "ubtech-ukit", "ubtech-cruzr-1s", "unitree-g1"],
    },
    {
        "slug": "ubtech-ugot", "group": "education", "details": ['machines/ubtech-ugot-d1.jpg', 'machines/ubtech-ugot-d2.jpg', 'machines/ubtech-ugot-d3.jpg'], "light": "machines/cut/ubtech-ugot.webp", "stage": "machines/ubtech-ugot-stage.jpg", "highlights": [('7 robot forms', 'One kit, rebuilt tool-free'), ('1 TOPS NPU', 'Quad Cortex-A55, GPU'), ('720p camera', 'ToF ranging, 9-axis IMU'), ('8 servos, 4 motors', 'Snap-fit joints and wheels'), ('Python and ROS 2', 'Open SDK'), ('6 USB-C ports', 'Plus USB-A and GPIO'), ('About 2 hours', '2600 mAh battery'), ('2.4-inch touchscreen', '3-mic far-field array')], "maker": "UBTECH", "name": "UBTECH UGOT",
        "kind": "STEM robotics kit", "status": "Sourced to order",
        "line": "One kit, seven robots. Edge AI, Python and ROS 2 for the programs that outgrow block coding.",
        "intro": "UGOT is a reconfigurable robotics kit: learners rebuild the same platform into rover, quadruped, balance and manipulator forms, then program sensing, motion and AI behaviour on top. More useful for iterative learning than a single-purpose classroom bot.",
        "hero": "machines/ubtech-ugot-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Tool-free modular rebuilds", "Seven robot forms, snap-fit assembly, under ten minutes to reconfigure. The lesson stays on design and iteration, not teardown."),
            ("Embedded AI and sensing", "1 TOPS NPU, 720p camera, ToF and IMU, so recognition, autonomy and path logic run on the robot itself."),
            ("Python, ROS 2 and expansion", "Python APIs, ROS 2, GPIO and USB-C expansion: from guided activities to multi-robot experiments."),
        ],
        "fits": [
            ("School STEM programs", "Upper-primary and secondary programs that need more than block coding on a fixed robot. For a humanoid instead, see Yanshee."),
            ("Makerspaces and robotics clubs", "Freedom to test chassis ideas, sensors and behaviours on one expandable kit."),
            ("Competitions", "Line following, terrain navigation, speed trials and rule-specific rebuilds."),
            ("Advanced classroom labs", "Introducing ROS 2, perception and multi-robot collaboration without research-platform cost."),
        ],
        "specs": [("Model", "UBTECH UGOT AI Robotic Kit"), ("Category", "Modular STEM robotics kit, AI classroom platform"), ("Robot forms", "7 transformable configurations from one kit"), ("Main controller", "Quad Cortex-A55 CPU, integrated GPU, 1 TOPS NPU"), ("Display", "2.4\" touchscreen, 4 RGB status LEDs"), ("Audio", "3-mic far-field array with noise reduction, 1 W speaker"), ("Sensors", "720p RGB camera, ToF ranging, 9-axis IMU"), ("Actuation", "8 servo joints, 4 wheel motors"), ("Expansion", "6 USB-C motor and sensor ports, USB-A 3.0, USB-A 2.0, USB-C, open GPIO header"), ("Battery", "2600 mAh, about 2 hours runtime, about 5 hours standby"), ("Development access", "Python, ROS 2, open SDK, Micro:bit, Arduino, Raspberry Pi, custom sensors")],
        "compare": None,
        "faq": [("Who is it for?", "Upper-primary, secondary and club-level programs, plus advanced STEM labs wanting something more open than entry-level coding robots."), ("Python and ROS 2?", "Yes, plus an open SDK and expansion for external boards and sensors."), ("Competitions and custom builds?", "One of its strongest uses: transformable chassis, expansion ports and AI tooling for iterative student-led builds."), ("How does it compare with uKit and Yanshee?", "uKit is the foundation kit, UGOT the modular and AI step up, Yanshee the humanoid.")],
        "price": "Quoted to order", "related": ["ubtech-yanshee", "ubtech-ukit", "unitree-g1"],
    },
    {
        "slug": "ubtech-ukit", "group": "education", "details": ['machines/ubtech-ukit-d1.jpg', 'machines/ubtech-ukit-d2.jpg', 'machines/ubtech-ukit-d3.jpg'], "light": "machines/cut/ubtech-ukit.webp", "stage": "machines/ubtech-ukit-stage.jpg", "highlights": [('Snap-together', 'No tools, no engineering overhead'), ('Servo modules', 'Motion from the first lesson'), ('Visual coding', 'Blocks before Python'), ('One-session builds', 'Build, code, reset, repeat'), ('Primary and lower secondary', 'The first step in the pathway'), ('Classroom durable', 'Repeated use, repeated groups'), ('Kit quantities', 'Planned for the class size'), ('Next step: UGOT', 'Then Yanshee')], "maker": "UBTECH", "name": "UBTECH uKit",
        "kind": "STEM education kit", "status": "Sourced to order",
        "line": "The kit a class can build, code and reuse in one session.",
        "intro": "uKit is the foundation robotics kit: snap-together parts, servo modules and visual coding for primary and lower-secondary programs. It sits before Yanshee and UGOT in a staged robotics pathway.",
        "hero": "machines/ubtech-ukit-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Modular building", "Snap-together parts and servo modules, repeatable classroom assembly. Structure and function, mechanism logic, sequencing."),
            ("Entry-level coding", "Visual programming and guided logic blocks: control flow, actions, timing and event-based behaviour."),
            ("Classroom-first", "Durable, repeatable, manageable setup for school timetables, clubs and workshops."),
        ],
        "fits": [
            ("Primary and lower secondary", "Build and program a robot in one session without engineering overhead. The next step is UGOT."),
            ("Clubs and workshops", "Modular tasks, fast resets, repeated sessions across age groups."),
            ("Libraries and makerspaces", "Approachable hardware for guided sessions and family STEM activities."),
            ("Teacher-led programs", "A structured kit that sits below Yanshee and UGOT in the pathway."),
        ],
        "specs": [("Product", "UBTECH uKit education robot kit"), ("Category", "STEM education kit, modular robotics kit for schools"), ("Learning focus", "Robot building, mechanical understanding, coding logic, introductory robotics"), ("Assembly", "Modular construction for repeated build-and-rebuild cycles"), ("Programming", "Visual coding for beginner robotics teaching"), ("Typical users", "Primary and lower-secondary students, training providers, libraries, community programs"), ("Delivery model", "Supplied as an education kit"), ("Note", "Exact kit composition varies by package and rollout")],
        "compare": None,
        "faq": [("Who is it for?", "Primary and lower-secondary learners moving from simple coding into practical robotics."), ("Coding classes and workshops?", "That's the main fit: teacher-led classes, after-school robotics, holiday workshops, makerspace sessions."), ("uKit or UGOT or Yanshee?", "uKit first. UGOT for modular and AI-led work, Yanshee for humanoid interaction and open development."), ("How is it supplied?", "As a kit, with classroom quantity planning and delivery coordination from us.")],
        "price": "Quoted to order", "related": ["ubtech-ugot", "ubtech-yanshee", "unitree-g1"],
    },
    {
        "slug": "coffee-robot", "page": "robot-coffee-machines/", "buy": "bpro", "details": ['machines/coffee-robot-d1.jpg', 'machines/coffee-robot-d2.jpg', 'machines/coffee-robot-d3.jpg'], "light": "machines/coffee-robot-light.jpg", "stage": "machines/coffee-robot-stage.jpg", "video": "machines/coffee-robot-stage.mp4", "video_poster": "machines/coffee-robot-stage-poster.jpg", "video_caption": "Dual-arm barista bar, a purple cup off the stack", "highlights": [('Output measured', 'On your menu, at commissioning'), ('About 2 m²', '1410 × 2200 × 1480 mm'), ('4000 W', 'AC 220 V, 50 Hz'), ('8 and 12 oz cups', 'Hot and iced'), ('App ordering', 'Or mini-program'), ('Caramel printing', 'Branded patterns on the cup'), ('JAKA and Dobot arms', 'Eversys and Dr.Coffee machines'), ('About two months', 'From order, DDU to port')], "pos": "50% 42%", "maker": "Wonder Robotics", "name": "Coffee and bar robots",
        "kind": "Robotic beverage station", "status": "On our floor",
        "line": "A barista or a bartender in about two square metres, and a show every time.",
        "intro": "Visible beverage preparation, app ordering, branded drinks and a compact station that fits reception, retail, exhibition and lounge spaces. Ours pours at the bar at 365 St Pauls Terrace. Formats run from a vending kiosk to a dual-arm barista bar and a robot bartender.",
        "hero": "tile-coffee.jpg", "hero_real": True, "gallery": ["machines/coffee-hero.jpg"],
        "features": [
            ("Branded drink presentation", "Preset and custom patterns, including caramel printing, so the coffee doubles as a brand touchpoint."),
            ("Digital ordering and pickup", "App or mini-program ordering runs the station as a managed kiosk, not a staffed counter."),
            ("Configurable stack", "Coffee machine selection, ice machine in or out, chocolate-powder printing, multiple milk lines."),
        ],
        "fits": [
            ("Retail and brand showcase", "Exhibitions, operator display zones and smart retail where visitors watch the drink made."),
            ("Premium waiting areas", "Banks, airports, VIP lounges and dealerships where beverage service supports dwell time."),
            ("Office buildings", "Lobby activations and managed visitor service with minimal operator input."),
            ("Public service", "Structured public settings with clear traffic flow and a controlled menu."),
        ],
        "specs": [("Formats", "Smart EFF vending kiosk · B Pro and B Standard dual-arm barista bars · T Standard robot bartender"), ("Voltage", "AC 220 V 50 Hz"), ("Rated power", "4000 W"), ("Installed size, showcase format", "1410 × 2200 × 1480 mm"), ("Cycle time", "About 70 seconds on the maker's showcase workflow; yours is measured on your menu"), ("Serve format", "8 oz and 12 oz cups"), ("Ordering", "App or mini-program"), ("Arm platforms", "JAKA Minicobo 6-axis on the showcase format; Dobot on the bartender"), ("Coffee machines", "Eversys on B Pro; Dr.Coffee F3 on B Standard; Dr.Coffee F200 on the kiosk"), ("Footprint", "About 2 square metres"), ("Options", "Ice machine, caramel and chocolate-powder printing, multiple milk lines"), ("Warranty", "One year"), ("Delivery", "About two months from order, DDU within 100 km of an Australian port")],
        "compare": ("The three formats", [("Smart EFF kiosk", "Dual arm, vending format, orange or black", "{{installed:eff}} installed"), ("B Pro bar", "Dual arm, Eversys, white or black", "{{installed:bpro}} installed"), ("B Standard bar", "Dual arm, Dr.Coffee F3", "{{installed:bstd}} installed"), ("T Standard bartender", "Dobot arm, ice, 3 syrups", "{{installed:bar}} installed")]),
        "faq": [("How fast is it?", "The maker's showcase workflow runs about 70 seconds a drink. Yours is measured on your menu when we commission it."), ("Branded drinks?", "Yes: preset and user-defined patterns, caramel printing, optional chocolate powder."), ("Can it be configured?", "Coffee machine, ice machine, printing and milk lines all change with the project."), ("Footprint?", "About two square metres, plus circulation, queue and utilities on site.")],
        "price": "From {{monthly:bar}} a month", "related": ["kitchen-robot", "custom-automation", "ubtech-cadebot"],
    },
    {
        "slug": "kitchen-robot", "page": "robot-kitchen-fitouts/", "buy": "fry,noo", "details": ['machines/kitchen-robot-d1.jpg', 'machines/kitchen-robot-d2.jpg', 'machines/kitchen-robot-d3.jpg'], "light": "machines/cut/kitchen-robot.webp", "stage": "machines/kitchen-robot-stage.jpg", "highlights": [('6 fry stoves', 'F Standard deep frying robot'), ('6 noodle stoves', 'N Standard noodle robot'), ('Dobot arms', 'Reach and payload matched to the line'), ('Built around the menu', 'Cooking module chosen for the output'), ('Guarded hot process', 'Separation scoped per kitchen'), ('Recipe sequencing', 'Timing and step transitions'), ('Fully autonomous option', 'Order to pass, as in our building'), ('About two months', 'From order, DDU to port')], "maker": "Wonder Robotics", "name": "Robot kitchens",
        "kind": "Kitchen automation", "status": "On our floor",
        "line": "An arm on a rail, fryers, noodle baths, an ingredient store. The one downstairs cooks the whole menu six days a week.",
        "intro": "Back-of-house automation for the repeated hot steps: deep frying, boiling, and connected lines with an ingredient store and a pass. Ours runs every day at 365 St Pauls Terrace; the next one is under construction for Little Red Dumpling on the Gold Coast.",
        "hero": "hero-kitchen.jpg", "hero_real": True, "gallery": ["machines/kitchen-hero.jpg"],
        "features": [
            ("Frying workflows", "Basket handling, timing and repeatable fryer output where consistency beats presentation."),
            ("Boiling lines", "Noodle, soup and cooking-line tasks with controlled timing and batch consistency."),
            ("Designed around the line", "The robot cell, the cooking equipment and the workflow arranged around your space, not a fixed box."),
        ],
        "fits": [
            ("Deep-fry automation", "The reference format: a fry station robot for high-repeat production around hot oil."),
            ("Boiling stations", "Soup, noodle and boiling processes where timing and ingredient order must hold."),
            ("Hybrid lines", "Frying plus transfer, pickup or staging: a broader handoff between cooking and the pass."),
            ("Fully autonomous kitchens", "Order to pass by machine, as at 365 St Pauls Terrace and the Little Red Dumpling build."),
        ],
        "specs": [("Formats", "N Standard noodle robot · F Standard deep frying robot · custom lines"), ("Noodle robot", "Dobot arm, 6 noodle stoves"), ("Deep frying robot", "Dobot arm, 6 frying stoves"), ("Cooking module", "Fry or boiling equipment selected around the menu and output"), ("Feeding and pickup", "Ingredient loading, basket transfer, staging and pickup points around operator flow"), ("Safety and guarding", "Guarding, separation and hot-process handling scoped per kitchen"), ("Control logic", "Timing, recipe sequence and step transitions around the real process"), ("Arm selection", "Reach, payload, mounting and end-effector matched to the task"), ("Warranty", "One year"), ("Delivery", "About two months from order, DDU within 100 km of an Australian port")],
        "compare": ("The two standard lines", [("N Standard noodle robot", "Dobot arm, 6 noodle stoves", "{{installed:noo}} installed"), ("F Standard deep frying robot", "Dobot arm, 6 frying stoves", "{{installed:fry}} installed")]),
        "faq": [("Only deep fry?", "No. Fry is the reference format; boiling, hybrid and fully autonomous lines are scoped the same way."), ("Can the layout follow our line?", "Yes: cell, equipment, pickup and workflow are configured around your kitchen, utilities and menu."), ("Frying and boiling in one project?", "Yes, when the workflow needs it: one step, or a connected sequence."), ("Which kitchens fit best?", "Repeated hot-process tasks, stable menu logic, and a clear need for consistency, safer handling or lower operator load.")],
        "price": "From {{monthly:fry}} a month", "related": ["coffee-robot", "custom-automation", "ubtech-cadebot"],
    },
    {
        "slug": "custom-automation", "group": "order", "light": "machines/cut/custom-automation.webp", "details": ['machines/custom-automation-d1.jpg', 'machines/custom-automation-d2.jpg', 'machines/custom-automation-d3.jpg'], "stage": "machines/custom-automation-stage.jpg", "highlights": [('Arm to the task', 'Reach, payload, mounting'), ('Tooling to the part', 'End-effector for the real handling'), ('Cell to the floor', 'Pickup, drop, staging, guarding'), ('Logic to the sequence', 'PLC, triggers, cycle targets'), ('Existing equipment kept', 'Conveyors and stations stay'), ('Assess, map, configure', 'Three steps to a scope'), ('Prototyped in the Valley', 'Our workshop first'), ('Installed on your floor', 'Then supported from Brisbane')], "maker": "Wonder Robotics", "name": "Custom automation",
        "kind": "Robotics engineering", "status": "Scoped first",
        "line": "A pallet, a fry basket, a bar dispenser. Drawn against your floor plan, built in the workshop here, run on our floor before it ships.",
        "intro": "Arm, tooling and mounting; the cell and its safety; the control logic that ties the sequence together. Three decisions, made around your equipment, layout and output target, in our workshop first.",
        "hero": "machines/custom-automation-light.jpg", "hero_real": False, "gallery": [],
        "features": [
            ("Arm, tooling and mounting", "Reach, payload, orientation, working area and end-effector chosen for the handling task."),
            ("Cell design and safety", "Pickup points, drop positions, staging, guarding and operator interaction arranged around the line."),
            ("Logic, sequencing and output", "PLC, software, triggers, step transitions, cycle targets and operator handoff around your sequence."),
        ],
        "fits": [
            ("Existing equipment", "Machines, conveyors or stations that must stay in the workflow."),
            ("Site layout", "Reach, mounting, guarding and access set by the real floor plan."),
            ("Process logic", "Pickup order, handoff, cycle timing and triggers specific to the job."),
            ("Non-standard formats", "When no coffee, kitchen or service-robot format matches the requirement."),
        ],
        "specs": [("Assess", "Define the task: what the arm moves, loads, places or operates, and the timing"), ("Map", "The surrounding cell: machines, stations, utilities, safety rules, operator handoff"), ("Configure", "Arm platform, tooling, layout and control logic chosen for the operating environment"), ("Delivered as", "A recommended arm cell, tooling and control scope, then the build")],
        "compare": None,
        "faq": [("When is this the right route?", "When the requirement doesn't map to a standard format, or depends heavily on your own equipment and layout."), ("Can the arm itself be customised?", "Yes: selection, reach, payload, mounting, tooling and how it interacts with the surrounding equipment."), ("What do you need for the first conversation?", "The task, target throughput, available space, safety constraints and the machines the arm works with."), ("Where is it built?", "Scoped and prototyped in our workshop in Fortitude Valley, then installed on your floor.")],
        "price": "Scoped first", "related": ["kitchen-robot", "coffee-robot", "ubtech-cruzr-y1"],
    },
    {
        "slug": "ai-agents", "group": "order", "highlights": [('One live workflow', 'Pilot, prove, then expand'), ('Grounded in your docs', 'SOPs, policy, product information'), ('Review gates', 'A person stays in charge'), ('CRM and helpdesk', 'Salesforce, HubSpot, Zendesk, Freshdesk'), ('ERP and finance', 'Xero, MYOB, internal databases'), ('Escalation rules', 'Act directly or hand over'), ('Monitoring', 'Usage signals and revision cycles'), ('Named owner', 'After handover, in your team')], "maker": "Wonder Robotics", "name": "AI agents",
        "kind": "Software", "status": "Scoped first",
        "line": "Invoice matching, approvals, support triage, and the vision that tells an arm when to stop. Runs on your data, and a person signs off.",
        "intro": "We connect an agent to the software you already run, ground it in your documentation and business rules, and deploy it into one live workflow with review points your team controls. Most projects prove themselves in one workflow before they grow.",
        "hero": None, "hero_real": False, "gallery": [],
        "features": [
            ("Knowledge", "SOPs, policy and product information, with document-grounded retrieval over your own material."),
            ("Controls", "Review gates, permission boundaries and human handoff, with a named owner after handover."),
            ("Tool integrations", "CRM, helpdesk, ERP, forms, databases and internal tools: Salesforce, HubSpot, Zendesk, Freshdesk, Xero, MYOB and custom software."),
        ],
        "fits": [
            ("Support triage and replies", "Classify requests, retrieve history, draft replies grounded in documentation, route exceptions."),
            ("Sales coordination", "Qualify leads, draft proposals and update the pipeline from CRM history and deal context."),
            ("Approvals and finance", "Purchase orders, contracts, leave, invoice matching and discrepancies, against documented rules."),
            ("Internal requests", "HR, IT and admin requests that follow policy, escalating only when a person must decide."),
        ],
        "specs": [("Map the live workflow", "What comes in, which systems, what the agent does, what done looks like"), ("Set boundaries", "Knowledge sources, tool access, where approval or review still sits"), ("Pilot in one workflow", "Live process, measured output quality, act directly versus escalate"), ("Production with ownership", "Monitoring, revision cycles and a business owner for day-to-day use")],
        "compare": None,
        "faq": [("Agent or chatbot?", "An agent works inside a process: retrieves context, follows rules, uses connected software, completes or hands over. A chatbot answers questions and stops."), ("Where do you start?", "Internal workflows: approvals, service requests, support triage, sales coordination, back-office processing."), ("Prototype first?", "Yes, a scoped pilot in one live workflow is the usual first step."), ("Customer-facing?", "Yes, when the process is well-scoped, knowledge is current and a person can step in quickly.")],
        "price": "Scoped first", "related": ["software", "custom-automation", "ubtech-cruzr-1s"],
    },
    {
        "slug": "software", "group": "order", "highlights": [('React and Next.js', 'Front ends people like using'), ('Node and Python', 'Services around your data'), ('PostgreSQL', 'Data model designed early'), ('REST and GraphQL', 'Documented contracts, webhooks'), ('Scoped first', 'Workflow, roles, integrations'), ('Staged build', 'Working software at every milestone'), ('Acceptance tested', 'Then deployed to production'), ('Handed over', 'Documentation your team can run on')], "maker": "Wonder Robotics", "name": "Software",
        "kind": "Custom software", "status": "Scoped first",
        "line": "The ordering, payment, stock and dispatch every robot here talks to, and the dashboard the manager watches on a phone. React, Node, Python, Postgres.",
        "intro": "Customer-facing platforms, internal tools, dashboards, APIs and the software behind robotics and AI agent deployments. React, Next.js, Node, Python, PostgreSQL, REST and GraphQL, built in stages with working software at each review.",
        "hero": None, "hero_real": False, "gallery": [],
        "features": [
            ("B2B platforms and portals", "Customer portals, partner platforms, booking flows, management consoles and account-based systems."),
            ("Internal systems", "Approval tools, workflow software, admin interfaces and operational dashboards, around the real process."),
            ("APIs and integration", "CRM, ERP, finance, document platforms and internal databases. REST, GraphQL and webhooks with documented contracts."),
        ],
        "fits": [
            ("Scope the workflow and users first", "Map the process, define roles, identify integrations, agree what done looks like."),
            ("Design before code", "UI and UX, data model, API contracts and stack decided early."),
            ("Build in stages", "Feature delivery with working software at each milestone and client review gates."),
            ("Test, deploy, hand over", "Acceptance testing, production deployment, documentation, and a team that can continue without us."),
        ],
        "specs": [("Stack", "React, Next.js, Node, Python, PostgreSQL, REST, GraphQL"), ("Delivery", "Scoped, built and handed over from Brisbane, with workshops and documentation"), ("Typical builds", "B2B platforms, internal systems, web applications, integrations"), ("Handover", "Acceptance testing, deployment, operational documentation")],
        "compare": None,
        "faq": [("When are you the right fit?", "When the software has to sit inside a live process, not when a template app would do."), ("How is it delivered?", "Requirements, design and build phases with review gates and working software at each milestone."), ("Do you integrate with what we have?", "Yes: CRM, ERP, finance, document platforms and internal databases."), ("What should we bring?", "The existing workflow, user groups, software stack, integration needs and launch goals.")],
        "price": "Scoped first", "related": ["ai-agents", "custom-automation", "kitchen-robot"],
    },
]

# (file in img/partners/, name). Marks go in as the files they came as: the
# makers and UniQuest from the corporate profile kit, the rest as supplied.
# No UQ mark on disk yet; it goes in when Jesse supplies it.
PARTNERS = [("ubtech-mark.png", "UBTECH"), ("unitree.png", "Unitree"), ("agibot.png", "AgiBot"), ("armhub.png", "ArmHub"),
            ("uniquest.png", "UniQuest"), ("qut.jpg", "QUT"), ("kuehne-nagel.jpg", "Kuehne+Nagel"), ("onyx-tyres.jpg", "Onyx Tyres"),
            ("powerskills-ai.jpg", "PowerSkills AI"), ("muzix-audio.jpg", "Muzix Audio"), ("stellaris-robotics.jpg", "Stellaris Robotics"),
            ("blue-sun-group.jpg", "Blue Sun Group"), ("little-red-dumplings.jpg", "Little Red Dumpling")]
